proxies:
  bungee-cord:
    online-mode: true
  proxy-protocol: false
  velocity:
    enabled: true
    online-mode: true
    secret: test
block-updates:
  disable-chorus-plant-updates: false
  disable-mushroom-block-updates: true
