package net.horizonsend.ion.server.features.starship

import net.horizonsend.ion.common.utils.text.colors.HEColorScheme.Companion.HE_MEDIUM_GRAY
import net.horizonsend.ion.common.utils.text.ofChildren
import net.horizonsend.ion.server.configuration.ConfigurationFiles
import net.horizonsend.ion.server.configuration.starship.StarshipTypeBalancing
import net.horizonsend.ion.server.features.progression.Levels
import net.horizonsend.ion.server.features.sidebar.SidebarIcon
import net.horizonsend.ion.server.features.starship.destruction.SinkProvider
import net.horizonsend.ion.server.features.world.IonWorld
import net.horizonsend.ion.server.features.world.WorldFlag
import net.horizonsend.ion.server.miscellaneous.utils.updateDisplayName
import net.horizonsend.ion.server.miscellaneous.utils.updateLore
import net.kyori.adventure.text.Component
import net.kyori.adventure.text.Component.empty
import net.kyori.adventure.text.Component.newline
import net.kyori.adventure.text.Component.text
import net.kyori.adventure.text.format.NamedTextColor.AQUA
import net.kyori.adventure.text.format.TextColor
import org.bukkit.Material
import org.bukkit.entity.Player
import org.bukkit.inventory.ItemStack
import java.util.function.Supplier
import kotlin.collections.setOf

enum class StarshipType(
	val displayName: String,
	val needsFuel: Boolean,
	val tech2: Boolean,
	val icon: String = SidebarIcon.GENERIC_STARSHIP_ICON.text,
	val color: String,
	val dynmapIcon: String = "anchor",

	val minSize: Int,
	val maxSize: Int,

	val minLevel: Int,
	val overridePermission: String,
	val requiredPermission: String? = null,

	val containerPercent: Double,
	val concretePercent: Double = 0.3,
	val crateLimitMultiplier: Double,

	val menuItemRaw: Supplier<ItemStack>,
	val displayInMainMenu: Boolean = true,
	val menuSubclasses: Supplier<List<StarshipType>> = Supplier { listOf() },
	val typeCategory: TypeCategory,

	val eventShip: Boolean = false,
	val powerOverrider: Double = 1.0,

	val requiredWorldFlags: Set<WorldFlag> = setOf(),
	val disallowedWorldFlags: Set<WorldFlag> = setOf(),

	val maxMiningLasers: Int = 0,
	val miningLaserTier: Int = 0,

	val sinkProvider: SinkProvider.SinkProviders,

	private val balancingSupplier: Supplier<StarshipTypeBalancing>
) {
	SPEEDER(
		displayName = "Speeder",
		needsFuel = false,
		tech2 = false,
		minSize = 25,
		maxSize = 100,
		minLevel = 1,
		containerPercent = 0.25,
		concretePercent = 0.0,
		crateLimitMultiplier = 0.125,
		menuItemRaw = { ItemStack(Material.DEAD_BUSH) },
		menuSubclasses = { listOf(AI_SPEEDER) },
		typeCategory = TypeCategory.SPECIALTY,
		color = "#ffff32",
		overridePermission = "ion.ships.override.1",
		powerOverrider = 0.0,
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::speeder,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_SPEEDER(
		displayName = "Speeder",
		needsFuel = false,
		tech2 = false,
		minSize = 25,
		maxSize = 100,
		minLevel = 1000,
		containerPercent = 0.5,
		crateLimitMultiplier = 0.125,
		menuItemRaw = { ItemStack(Material.SPONGE) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.SPECIALTY,
		color = "#ffff32",
		powerOverrider = 0.0,
		concretePercent = 0.0,
		requiredPermission = "ion.ships.ai",
        overridePermission = "ion.ships.ai.speeder",
		sinkProvider = SinkProvider.SinkProviders.NO_REMOVAL,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::speeder,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	STARFIGHTER(
		displayName = "Starfighter",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.STARFIGHTER_ICON.text,
		minSize = 350,
		maxSize = 500,
		minLevel = 1,
		containerPercent = 0.025,
		concretePercent = 0.15,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.IRON_NUGGET) },
		menuSubclasses = { listOf(AI_STARFIGHTER, INTERCEPTOR, RECON_STARFIGHTER, SCRAMBLER_STARFIGHTER) },
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#ff8000",
		overridePermission = "ion.ships.override.1",
		dynmapIcon = "starfighter",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::starfighter,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_STARFIGHTER(
		displayName = "Starfighter",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.AI_STARFIGHTER_ICON.text,
		minSize = 150,
		maxSize = 500,
		minLevel = 1000,
		containerPercent = 0.5,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.SPONGE) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#ff8000",
		dynmapIcon = "starfighter",
		concretePercent = 0.0,
		requiredPermission = "ion.ships.ai",
        overridePermission = "ion.ships.ai.starfighter",
		sinkProvider = SinkProvider.SinkProviders.NO_REMOVAL,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::starfighter,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	SCRAMBLER_STARFIGHTER(
		displayName = "Scrambler",
		needsFuel = false,
		tech2 = true,
		icon = SidebarIcon.STARFIGHTER_ICON.text,
		minSize = 250,
		maxSize = 500,
		minLevel = 1,
		containerPercent = 0.025,
		concretePercent = 0.15,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.GOLD_NUGGET) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#ff8000",
		overridePermission = "ion.ships.override.1",
		dynmapIcon = "starfighter",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::scramblerStarfighter,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	RECON_STARFIGHTER(
		displayName = "Recon Fighter",
		needsFuel = false,
		tech2 = true,
		icon = SidebarIcon.STARFIGHTER_ICON.text,
		minSize = 250,
		maxSize = 500,
		minLevel = 1,
		containerPercent = 0.025,
		concretePercent = 0.0,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.COPPER_INGOT) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#ff8000",
		overridePermission = "ion.ships.override.1",
		dynmapIcon = "starfighter",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::reconStarfighter,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	INTERCEPTOR(
		displayName = "Interceptor",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.INTERCEPTOR_ICON.text,
		minSize = 150,
		maxSize = 350,
		minLevel = 1000,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		concretePercent = 0.15,
		menuItemRaw = { ItemStack(Material.GHAST_TEAR) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#ff8000",
		overridePermission = "ion.ships.override.1",
		dynmapIcon = "interceptor",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::interceptor,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_INTERCEPTOR(
		displayName = "Interceptor",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.INTERCEPTOR_ICON.text,
		minSize = 150,
		maxSize = 350,
		minLevel = 1,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		concretePercent = 0.0,
		menuItemRaw = { ItemStack(Material.SPONGE) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#ff8000",
		requiredPermission = "ion.ships.ai",
		overridePermission = "ion.ships.override.1",
		dynmapIcon = "interceptor",
		sinkProvider = SinkProvider.SinkProviders.NO_REMOVAL,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::interceptor,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	GUNSHIP(
		displayName = "Gunship",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.GUNSHIP_ICON.text,
		minSize = 500,
		maxSize = 2000,
		minLevel = 10,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.IRON_INGOT) },
		menuSubclasses = { listOf(AI_GUNSHIP, ASSAULT_GUNSHIP, INTERDICTOR_GUNSHIP) },
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#ff4000",
		overridePermission = "ion.ships.override.10",
		dynmapIcon = "gunship",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::gunship,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	ASSAULT_GUNSHIP(
		displayName = "Assault Gunship",
		needsFuel = false,
		tech2 = true,
		icon = SidebarIcon.GUNSHIP_ICON.text,
		minSize = 1000,
		maxSize = 2500,
		minLevel = 10,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.GOLD_INGOT) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#ff4000",
		overridePermission = "ion.ships.override.10",
		dynmapIcon = "gunship",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::assaultGunship,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	INTERDICTOR_GUNSHIP(
		displayName = "Interdictor Gunship",
		needsFuel = false,
		tech2 = true,
		icon = SidebarIcon.GUNSHIP_ICON.text,
		minSize = 1000,
		maxSize = 2500,
		minLevel = 10,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.NETHERITE_INGOT) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#ff4000",
		overridePermission = "ion.ships.override.10",
		dynmapIcon = "gunship",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::interdictorGunship,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_GUNSHIP(
		displayName = "Gunship",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.AI_GUNSHIP_ICON.text,
		minSize = 500,
		maxSize = 2000,
		minLevel = 1000,
		containerPercent = 0.5,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.SPONGE) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#ff4000",
		dynmapIcon = "gunship",
		concretePercent = 0.0,
		requiredPermission = "ion.ships.ai",
        overridePermission = "ion.ships.ai.gunship",
		sinkProvider = SinkProvider.SinkProviders.NO_REMOVAL,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::gunship,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	CORVETTE(
		displayName = "Corvette",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.CORVETTE_ICON.text,
		minSize = 2000,
		maxSize = 4000,
		minLevel = 20,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.IRON_TRAPDOOR) },
		menuSubclasses = { listOf(AI_CORVETTE, AI_CORVETTE_LOGISTIC, INTERDICTOR_CORVETTE, STASIS_CORVETTE, ASSAULT_CORVETTE, LOGISTICS_CORVETTE) },
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#ff0000",
		overridePermission = "ion.ships.override.20",
		dynmapIcon = "corvette",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::corvette,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_CORVETTE(
		displayName = "Corvette",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.AI_CORVETTE_ICON.text,
		minSize = 2000,
		maxSize = 4000,
		minLevel = 1000,
		containerPercent = 0.5,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.SPONGE) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#ff0000",
		dynmapIcon = "corvette",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		concretePercent = 0.0,
		requiredPermission = "ion.ships.ai",
        overridePermission = "ion.ships.ai.corvette",
		sinkProvider = SinkProvider.SinkProviders.NO_REMOVAL,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::corvette,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_CORVETTE_LOGISTIC(
		displayName = "Logistic Corvette",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.AI_CORVETTE_ICON.text,
		minSize = 2000,
		maxSize = 4000,
		minLevel = 1000,
		containerPercent = 0.5,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.IRON_DOOR) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#ff0000",
		dynmapIcon = "corvette",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		concretePercent = 0.0,
		requiredPermission = "ion.ships.ai",
        overridePermission = "ion.ships.ai.corvette",
		sinkProvider = SinkProvider.SinkProviders.NO_REMOVAL,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::corvette,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	INTERDICTOR_CORVETTE(
		displayName = "Interdictor Corvette",
		needsFuel = true,
		tech2 = true,
		icon = SidebarIcon.CORVETTE_ICON.text,
		minSize = 2500,
		maxSize = 4500,
		minLevel = 20,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.PALE_OAK_TRAPDOOR) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#ff0000",
		overridePermission = "ion.ships.override.20",
		dynmapIcon = "corvette",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::interdictorCorvette,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	STASIS_CORVETTE(
		displayName = "Stasis Corvette",
		needsFuel = true,
		tech2 = true,
		icon = SidebarIcon.CORVETTE_ICON.text,
		minSize = 2500,
		maxSize = 4500,
		minLevel = 20,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.COPPER_TRAPDOOR) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#ff0000",
		overridePermission = "ion.ships.override.20",
		dynmapIcon = "corvette",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::stasisCorvette,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	ASSAULT_CORVETTE(
		displayName = "Assault Corvette",
		needsFuel = true,
		tech2 = true,
		icon = SidebarIcon.CORVETTE_ICON.text,
		minSize = 2500,
		maxSize = 4500,
		minLevel = 20,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.JUNGLE_TRAPDOOR) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#ff0000",
		overridePermission = "ion.ships.override.20",
		dynmapIcon = "corvette",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::assaultCorvette,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	LOGISTICS_CORVETTE(
		displayName = "Logistics Corvette",
		needsFuel = true,
		tech2 = true,
		icon = SidebarIcon.CORVETTE_ICON.text,
		minSize = 2500,
		maxSize = 4500,
		minLevel = 20,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.OXIDIZED_COPPER_TRAPDOOR) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#ff0000",
		overridePermission = "ion.ships.override.20",
		dynmapIcon = "corvette",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::logisticsCorvette,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	FRIGATE(
		displayName = "Frigate",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.FRIGATE_ICON.text,
		minSize = 4000,
		maxSize = 8000,
		minLevel = 40,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.IRON_DOOR) },
		menuSubclasses = { listOf(AI_FRIGATE, AI_CORVETTE_LOGISTIC, ASSAULT_FRIGATE, BLACK_OPS_FRIGATE, MISSILE_FRIGATE) },
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#c00000",
		overridePermission = "ion.ships.override.40",
		dynmapIcon = "frigate",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::frigate,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_FRIGATE(
		displayName = "Frigate",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.AI_FRIGATE_ICON.text,
		minSize = 4000,
		maxSize = 8000,
		minLevel = 1000,
		containerPercent = 0.5,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.SPONGE) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#c00000",
		dynmapIcon = "frigate",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		concretePercent = 0.0,
		requiredPermission = "ion.ships.ai",
        overridePermission = "ion.ships.ai.frigate",
		sinkProvider = SinkProvider.SinkProviders.AI_LARGE,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::frigate,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	ASSAULT_FRIGATE(
		displayName = "Assault Frigate",
		needsFuel = true,
		tech2 = true,
		icon = SidebarIcon.FRIGATE_ICON.text,
		minSize = 6500,
		maxSize = 8500,
		minLevel = 40,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.OAK_DOOR) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#c00000",
		overridePermission = "ion.ships.override.40",
		dynmapIcon = "frigate",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::assaultFrigate,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	BLACK_OPS_FRIGATE(
		displayName = "Black Ops Frigate",
		needsFuel = true,
		tech2 = true,
		icon = SidebarIcon.FRIGATE_ICON.text,
		minSize = 6500,
		maxSize = 8500,
		minLevel = 40,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.COPPER_DOOR) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#c00000",
		overridePermission = "ion.ships.override.40",
		dynmapIcon = "frigate",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::blackOpsFrigate,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	MISSILE_FRIGATE(
		displayName = "Missile Frigate",
		needsFuel = true,
		tech2 = true,
		icon = SidebarIcon.FRIGATE_ICON.text,
		minSize = 6500,
		maxSize = 8500,
		minLevel = 40,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.PALE_OAK_DOOR) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#c00000",
		overridePermission = "ion.ships.override.40",
		dynmapIcon = "frigate",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::missileFrigate,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	DESTROYER(
		displayName = "Destroyer",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.DESTROYER_ICON.text,
		minSize = 8000,
		maxSize = 12000,
		minLevel = 60,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.IRON_BLOCK) },
		menuSubclasses = { listOf(AI_DESTROYER, ASSAULT_DESTROYER, INTERDICTOR_DESTROYER) },
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#800000",
		overridePermission = "ion.ships.override.60",
		dynmapIcon = "destroyer",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::destroyer,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_DESTROYER(
		displayName = "Destroyer",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.AI_DESTROYER_ICON.text,
		minSize = 8000,
		maxSize = 12000,
		minLevel = 1000,
		containerPercent = 0.5,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.SPONGE) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#800000",
		dynmapIcon = "destroyer",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		concretePercent = 0.0,
		requiredPermission = "ion.ships.ai",
        overridePermission = "ion.ships.ai.destroyer",
		sinkProvider = SinkProvider.SinkProviders.AI_LARGE,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::destroyer,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	ASSAULT_DESTROYER(
		displayName = "Assault Destroyer",
		needsFuel = true,
		tech2 = true,
		icon = SidebarIcon.DESTROYER_ICON.text,
		minSize = 9500,
		maxSize = 12500,
		minLevel = 60,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.COPPER_BLOCK) },
		typeCategory = TypeCategory.WAR_SHIP,
		displayInMainMenu = false,
		color = "#800000",
		overridePermission = "ion.ships.override.60",
		dynmapIcon = "destroyer",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::assaultDestroyer,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	INTERDICTOR_DESTROYER(
		displayName = "Interdictor Destroyer",
		needsFuel = true,
		tech2 = true,
		icon = SidebarIcon.DESTROYER_ICON.text,
		minSize = 9500,
		maxSize = 12500,
		minLevel = 60,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.DIAMOND_BLOCK) },
		typeCategory = TypeCategory.WAR_SHIP,
		displayInMainMenu = false,
		color = "#800000",
		overridePermission = "ion.ships.override.60",
		dynmapIcon = "destroyer",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::interdictorDestroyer,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	CRUISER(
		displayName = "Cruiser",
		needsFuel = true,
		tech2 = false,
		icon = SidebarIcon.BATTLECRUISER_ICON.text,
		minSize = 12000,
		maxSize = 16000,
		minLevel = 70,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { net.horizonsend.ion.server.core.registration.keys.CustomItemKeys.STEEL_PLATE.getValue().constructItemStack() },
		menuSubclasses = { listOf(AI_CRUISER, LOGISTICS_CRUISER, MISSILE_CRUISER) },
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#FFD700",
		overridePermission = "ion.ships.override.70",
		dynmapIcon = "cruiser",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::cruiser,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_CRUISER(
		displayName = "Cruiser",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.AI_BATTLECRUISER_ICON.text,
		minSize = 12000,
		maxSize = 16000,
		minLevel = 1000,
		containerPercent = 0.5,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.SPONGE) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#FFD700",
		dynmapIcon = "cruiser",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		concretePercent = 0.0,
		requiredPermission = "ion.ships.ai",
        overridePermission = "ion.ships.ai.cruiser",
		sinkProvider = SinkProvider.SinkProviders.AI_LARGE,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::cruiser,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	LOGISTICS_CRUISER(
		displayName = "Logistics Cruiser",
		needsFuel = true,
		tech2 = true,
		icon = SidebarIcon.BATTLECRUISER_ICON.text,
		minSize = 13500,
		maxSize = 16000,
		minLevel = 95,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { net.horizonsend.ion.server.core.registration.keys.CustomItemKeys.STEEL_INGOT.getValue().constructItemStack() },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#FFD700",
		overridePermission = "ion.ships.override.70",
		dynmapIcon = "cruiser",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::logisticsCruiser,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	MISSILE_CRUISER(
		displayName = "Missile Cruiser",
		needsFuel = true,
		tech2 = true,
		icon = SidebarIcon.BATTLECRUISER_ICON.text,
		minSize = 13500,
		maxSize = 16000,
		minLevel = 95,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { net.horizonsend.ion.server.core.registration.keys.CustomItemKeys.ALUMINUM_INGOT.getValue().constructItemStack() },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#FFD700",
		overridePermission = "ion.ships.override.70",
		dynmapIcon = "cruiser",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::missileCruiser,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	BATTLECRUISER(
		displayName = "Battlecruiser",
		needsFuel = true,
		tech2 = false,
		icon = SidebarIcon.BATTLECRUISER_ICON.text,
		minSize = 16000,
		maxSize = 20000,
		minLevel = 80,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.0,
		menuItemRaw = { net.horizonsend.ion.server.core.registration.keys.CustomItemKeys.STEEL_BLOCK.getValue().constructItemStack() },
		menuSubclasses = { listOf(AI_BATTLECRUISER, LANCER_BATTLECRUISER) },
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#0c5ce8",
		dynmapIcon = "battlecruiser",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		overridePermission = "ion.ships.override.80",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		requiredWorldFlags = setOf(WorldFlag.SPACE_WORLD),
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::battlecruiser,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_BATTLECRUISER(
		displayName = "Battlecruiser",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.AI_BATTLESHIP_ICON.text,
		minSize = 12000,
		maxSize = 20000,
		minLevel = 1000,
		containerPercent = 0.5,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.SPONGE) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#0c5ce8",
		dynmapIcon = "battlecruiser",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		concretePercent = 0.0,
		requiredPermission = "ion.ships.ai",
        overridePermission = "ion.ships.ai.battlecruiser",
		sinkProvider = SinkProvider.SinkProviders.AI_LARGE,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::battlecruiser,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	LANCER_BATTLECRUISER(
		displayName = "Lancer",
		needsFuel = true,
		tech2 = true,
		icon = SidebarIcon.BATTLECRUISER_ICON.text,
		minSize = 25000,
		maxSize = 32000,
		minLevel = 100,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.0,
		menuItemRaw = { net.horizonsend.ion.server.core.registration.keys.CustomItemKeys.ALUMINUM_BLOCK.getValue().constructItemStack() },
		typeCategory = TypeCategory.WAR_SHIP,
		displayInMainMenu = false,
		color = "#0c5ce8",
		dynmapIcon = "battlecruiser",
		maxMiningLasers = 1,
		miningLaserTier = 1,
		overridePermission = "ion.ships.override.80",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		requiredWorldFlags = setOf(WorldFlag.SPACE_WORLD),
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::lancerBattlecruiser,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	BATTLESHIP(
		displayName = "Battleship",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.BATTLESHIP_ICON.text,
		minSize = 20000,
		maxSize = 32000,
		minLevel = 1000,
		containerPercent = 0.015,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { net.horizonsend.ion.server.core.registration.keys.CustomItemKeys.STEEL_MODULE.getValue().constructItemStack() },
		menuSubclasses = { listOf(AI_BATTLESHIP) },
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#0c1cff",
		overridePermission = "ion.ships.override.battleship",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::battleship,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_BATTLESHIP(
		displayName = "Battleship",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.AI_BATTLESHIP_ICON.text,
		minSize = 20000,
		maxSize = 32000,
		minLevel = 1000,
		containerPercent = 0.5,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.SPONGE) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#0c1cff",
		concretePercent = 0.0,
		requiredPermission = "ion.ships.ai",
        overridePermission = "ion.ships.ai.battleship",
		sinkProvider = SinkProvider.SinkProviders.AI_LARGE,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::battleship,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	DREADNOUGHT(
		displayName = "Dreadnought",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.DREADNOUGHT_ICON.text,
		minSize = 32000,
		maxSize = 48000,
		minLevel = 1000,
		containerPercent = 0.015,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { net.horizonsend.ion.server.core.registration.keys.CustomItemKeys.STEEL_ASSEMBLY.getValue().constructItemStack() },
		menuSubclasses = { listOf(AI_DREADNOUGHT) },
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#320385",
		overridePermission = "ion.ships.override.dreadnought",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::dreadnought,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_DREADNOUGHT(
		displayName = "Dreadnought",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.AI_DREADNOUGHT_ICON.text,
		minSize = 32000,
		maxSize = 48000,
		minLevel = 1000,
		containerPercent = 0.5,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.SPONGE) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.WAR_SHIP,
		color = "#320385",
		concretePercent = 0.0,
		requiredPermission = "ion.ships.ai",
        overridePermission = "ion.ships.ai.dreadnought",
		sinkProvider = SinkProvider.SinkProviders.AI_LARGE,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::dreadnought,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	TANK(
		displayName = "Tank",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.STARFIGHTER_ICON.text,
		minSize = 50,
		maxSize = 500,
		minLevel = 1000,
		containerPercent = 0.025,
		crateLimitMultiplier = 0.0,
		concretePercent = 0.0,
		menuItemRaw = { net.horizonsend.ion.server.core.registration.keys.CustomItemKeys.GAS_CANISTER_EMPTY.getValue().constructItemStack() },
		typeCategory = TypeCategory.SPECIALTY,
		color = "#ff8000",
		overridePermission = "ion.ships.tank",
		dynmapIcon = "starfighter",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::tank,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	SHUTTLE(
		displayName = "Shuttle",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.SHUTTLE_ICON.text,
		minSize = 100,
		maxSize = 1000,
		minLevel = 1,
		concretePercent = 0.10,
		containerPercent = 0.075,
		crateLimitMultiplier = 1.0,
		menuItemRaw = { ItemStack(Material.PRISMARINE_SHARD) },
		menuSubclasses = { listOf(AI_SHUTTLE) },
		typeCategory = TypeCategory.TRADE_SHIP,
		color = "#008033",
		overridePermission = "ion.ships.override.1",
		powerOverrider = 0.7,
		maxMiningLasers = 1,
		miningLaserTier = 1,
		dynmapIcon = "shuttle",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::shuttle,
	),
	AI_SHUTTLE(
		displayName = "Shuttle",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.AI_SHUTTLE_ICON.text,
		minSize = 100,
		maxSize = 1000,
		minLevel = 1000,
		containerPercent = 0.045,
		crateLimitMultiplier = 1.0,
		menuItemRaw = { ItemStack(Material.SPONGE) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.TRADE_SHIP,
		color = "#008033",
		powerOverrider = 0.7,
		maxMiningLasers = 1,
		miningLaserTier = 1,
		dynmapIcon = "shuttle",
		concretePercent = 0.0,
		requiredPermission = "ion.ships.ai",
        overridePermission = "ion.ships.ai.shuttle",
		sinkProvider = SinkProvider.SinkProviders.NO_REMOVAL,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::shuttle,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	TRANSPORT(
		displayName = "Transport",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.TRANSPORT_ICON.text,
		minSize = 1000,
		maxSize = 2000,
		minLevel = 10,
		concretePercent = 0.10,
		containerPercent = 0.075,
		crateLimitMultiplier = 1.0,
		menuItemRaw = { ItemStack(Material.PRISMARINE_CRYSTALS) },
		menuSubclasses = { listOf(AI_TRANSPORT) },
		typeCategory = TypeCategory.TRADE_SHIP,
		color = "#008066",
		overridePermission = "ion.ships.override.10",
		powerOverrider = 0.7,
		maxMiningLasers = 1,
		miningLaserTier = 2,
		dynmapIcon = "transport",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::transport,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_TRANSPORT(
		displayName = "Transport",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.AI_TRANSPORT_ICON.text,
		minSize = 1000,
		maxSize = 2000,
		minLevel = 1000,
		containerPercent = 0.045,
		crateLimitMultiplier = 1.0,
		menuItemRaw = { ItemStack(Material.SPONGE) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.TRADE_SHIP,
		color = "#008066",
		powerOverrider = 0.7,
		maxMiningLasers = 1,
		miningLaserTier = 2,
		dynmapIcon = "transport",
		concretePercent = 0.0,
		requiredPermission = "ion.ships.ai",
        overridePermission = "ion.ships.ai.transport",
		sinkProvider = SinkProvider.SinkProviders.NO_REMOVAL,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::transport,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	LIGHT_FREIGHTER(
		displayName = "Light Freighter",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.LIGHT_FREIGHTER_ICON.text,
		minSize = 2000,
		maxSize = 4000,
		minLevel = 20,
		concretePercent = 0.10,
		containerPercent = 0.075,
		crateLimitMultiplier = 1.0,
		menuItemRaw = { ItemStack(Material.PRISMARINE_SLAB) },
		menuSubclasses = { listOf(AI_LIGHT_FREIGHTER, BLOCKADE_RUNNER) },
		typeCategory = TypeCategory.TRADE_SHIP,
		color = "#008099",
		overridePermission = "ion.ships.override.20",
		powerOverrider = 0.7,
		maxMiningLasers = 2,
		miningLaserTier = 2,
		dynmapIcon = "light_freighter",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::lightFreighter,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	BLOCKADE_RUNNER(
		displayName = "Blockade Runner",
		needsFuel = true,
		tech2 = true,
		icon = SidebarIcon.LIGHT_FREIGHTER_ICON.text,
		minSize = 2500,
		maxSize = 4500,
		minLevel = 50,
		concretePercent = 0.10,
		containerPercent = 0.075,
		displayInMainMenu = false,
		crateLimitMultiplier = 2.0,
		menuItemRaw = { ItemStack(Material.PRISMARINE_SLAB) },
		typeCategory = TypeCategory.TRADE_SHIP,
		color = "#008099",
		overridePermission = "ion.ships.override.20",
		powerOverrider = 0.7,
		maxMiningLasers = 2,
		miningLaserTier = 2,
		dynmapIcon = "light_freighter",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::blockadeRunner,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_LIGHT_FREIGHTER(
		displayName = "Light Freighter",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.AI_LIGHT_FREIGHTER_ICON.text,
		minSize = 2000,
		maxSize = 4000,
		minLevel = 1000,
		containerPercent = 0.045,
		crateLimitMultiplier = 1.0,
		menuItemRaw = { ItemStack(Material.SPONGE) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.TRADE_SHIP,
		color = "#008099",
		powerOverrider = 0.7,
		maxMiningLasers = 2,
		miningLaserTier = 2,
		dynmapIcon = "light_freighter",
		concretePercent = 0.0,
		requiredPermission = "ion.ships.ai",
        overridePermission = "ion.ships.ai.light_freighter",
		sinkProvider = SinkProvider.SinkProviders.NO_REMOVAL,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::lightFreighter,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	MEDIUM_FREIGHTER(
		displayName = "Medium Freighter",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.MEDIUM_FREIGHTER_ICON.text,
		minSize = 4000,
		maxSize = 8000,
		minLevel = 40,
		concretePercent = 0.10,
		containerPercent = 0.045,
		crateLimitMultiplier = 1.0,
		menuItemRaw = { ItemStack(Material.PRISMARINE_STAIRS) },
		typeCategory = TypeCategory.TRADE_SHIP,
		color = "#0080cc",
		powerOverrider = 0.7,
		maxMiningLasers = 4,
		miningLaserTier = 3,
		dynmapIcon = "medium_freighter",
		overridePermission = "ion.ships.override.40",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::mediumFreighter,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_MEDIUM_FREIGHTER(
		displayName = "Medium Freighter",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.MEDIUM_FREIGHTER_ICON.text,
		minSize = 4000,
		maxSize = 8000,
		minLevel = 1000,
		concretePercent = 0.0,
		containerPercent = 0.045,
		crateLimitMultiplier = 1.0,
		menuItemRaw = { ItemStack(Material.SPONGE) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.TRADE_SHIP,
		color = "#0080cc",
		powerOverrider = 0.7,
		maxMiningLasers = 4,
		miningLaserTier = 3,
		dynmapIcon = "medium_freighter",
		requiredPermission = "ion.ships.ai",
		overridePermission = "ion.ships.ai.medium_freighter",
		sinkProvider = SinkProvider.SinkProviders.AI_LARGE,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::mediumFreighter,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	HEAVY_FREIGHTER(
		displayName = "Heavy Freighter",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.HEAVY_FREIGHTER_ICON.text,
		minSize = 8000,
		maxSize = 12000,
		minLevel = 60,
		concretePercent = 0.1,
		containerPercent = 0.045,
		crateLimitMultiplier = 1.0,
		menuItemRaw = { ItemStack(Material.PRISMARINE) },
		menuSubclasses = { listOf(AI_HEAVY_FREIGHTER) },
		typeCategory = TypeCategory.TRADE_SHIP,
		color = "#0080ff",
		overridePermission = "ion.ships.override.60",
		powerOverrider = 0.7,
		maxMiningLasers = 6,
		miningLaserTier = 3,
		dynmapIcon = "heavy_freighter",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::heavyFreighter,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_HEAVY_FREIGHTER(
		displayName = "Heavy Freighter",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.AI_HEAVY_FREIGHTER_ICON.text,
		minSize = 8000,
		maxSize = 12000,
		minLevel = 1000,
		containerPercent = 0.045,
		crateLimitMultiplier = 1.0,
		menuItemRaw = { ItemStack(Material.SPONGE) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.TRADE_SHIP,
		color = "#0080ff",
		powerOverrider = 0.7,
		maxMiningLasers = 6,
		miningLaserTier = 3,
		dynmapIcon = "heavy_freighter",
		concretePercent = 0.0,
		requiredPermission = "ion.ships.ai",
        overridePermission = "ion.ships.ai.heavy_freighter",
		sinkProvider = SinkProvider.SinkProviders.AI_LARGE,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::heavyFreighter,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	BARGE(
		displayName = "Barge",
		needsFuel = true,
		tech2 = false,
		icon = SidebarIcon.BARGE_ICON.text,
		minSize = 16000,
		maxSize = 20000,
		minLevel = 80,
		concretePercent = 0.1, // I foresee no issues with this
		containerPercent = 0.075,
		crateLimitMultiplier = 0.0,
		menuItemRaw = { ItemStack(Material.SEA_LANTERN) },
		menuSubclasses = { listOf(AI_BARGE, JUMP_FREIGHTER, INDUSTRIAL_COMMAND_SHIP) },
		typeCategory = TypeCategory.TRADE_SHIP,
		color = "#0c5ce8",
		dynmapIcon = "barge",
		maxMiningLasers = 10,
		miningLaserTier = 3,
		overridePermission = "ion.ships.override.80",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		requiredWorldFlags = setOf(WorldFlag.SPACE_WORLD),
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::barge,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	JUMP_FREIGHTER(
		displayName = "Jump Freighter",
		needsFuel = true,
		tech2 = true,
		icon = SidebarIcon.BARGE_ICON.text,
		minSize = 24000,
		maxSize = 32000,
		minLevel = 90,
		concretePercent = 0.1,
		containerPercent = 0.02,
		crateLimitMultiplier = 3.0,
		menuItemRaw = { ItemStack(Material.SEA_LANTERN) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.TRADE_SHIP,
		color = "#0c5ce8",
		dynmapIcon = "barge",
		maxMiningLasers = 0,
		miningLaserTier = 0,
		overridePermission = "ion.ships.override.80",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		requiredWorldFlags = setOf(WorldFlag.SPACE_WORLD),
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::jumpFreighter,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	INDUSTRIAL_COMMAND_SHIP(
		displayName = "Industrial Command Ship",
		needsFuel = true,
		tech2 = true,
		icon = SidebarIcon.BARGE_ICON.text,
		minSize = 24000,
		maxSize = 32000,
		minLevel = 95,
		concretePercent = 0.1, // I foresee no issues with this
		containerPercent = 0.075,
		crateLimitMultiplier = 0.0,
		menuItemRaw = { ItemStack(Material.SEA_LANTERN) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.TRADE_SHIP,
		color = "#0c5ce8",
		dynmapIcon = "barge",
		maxMiningLasers = 14,
		miningLaserTier = 4,
		overridePermission = "ion.ships.override.80",
		sinkProvider = SinkProvider.SinkProviders.PLAYER,
		requiredWorldFlags = setOf(WorldFlag.SPACE_WORLD),
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::industrialCommandShip,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_BARGE(
		displayName = "Barge",
		needsFuel = false,
		tech2 = false,
		icon = SidebarIcon.BARGE_ICON.text,
		minSize = 16000,
		maxSize = 20000,
		minLevel = 1000,
		containerPercent = 0.075,
		crateLimitMultiplier = 0.0,
		menuItemRaw = { ItemStack(Material.SPONGE) },
		displayInMainMenu = false,
		typeCategory = TypeCategory.TRADE_SHIP,
		color = "#0c5ce8",
		dynmapIcon = "barge",
		maxMiningLasers = 10,
		miningLaserTier = 4,
		concretePercent = 0.0,
		requiredPermission = "ion.ships.ai",
        overridePermission = "ion.ships.ai.barge",
		sinkProvider = SinkProvider.SinkProviders.AI_LARGE,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::barge,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	PLATFORM(
		displayName = "Platform",
		needsFuel = false,
		tech2 = false,
		minSize = 25,
		maxSize = 2000000,
		minLevel = 1,
		containerPercent = 100.0,
		crateLimitMultiplier = 100.0,
		concretePercent = 0.0,
		menuItemRaw = { ItemStack(Material.BEDROCK) },
		typeCategory = TypeCategory.MISC,
		color = "#ffffff",
		overridePermission = "ion.ships.platform",
		powerOverrider = 0.0,
		sinkProvider = SinkProvider.SinkProviders.NO_REMOVAL,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::platform,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	UNIDENTIFIEDSHIP(
		displayName = "UnidentifiedShip",
		needsFuel = false,
		tech2 = false,
		minSize = 25,
		maxSize = 250000,
		minLevel = 1000,
		containerPercent = 100.0,
		concretePercent = 0.0,
		crateLimitMultiplier = 100.0,
		menuItemRaw = { ItemStack(Material.MUD_BRICKS) },
		typeCategory = TypeCategory.MISC,
		color = "#d0e39d",
		overridePermission = "ion.ships.eventship",
		eventShip = true,
		powerOverrider = 2.0,
		sinkProvider = SinkProvider.SinkProviders.NO_REMOVAL,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::unidentified,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	TESTINGSHIP(
	displayName = "TestingShip",
	needsFuel = false,
	tech2 = false,
	minSize = 25,
	maxSize = 250000,
	minLevel = 1000,
	containerPercent = 100.0,
	concretePercent = 0.0,
	crateLimitMultiplier = 100.0,
	menuItemRaw = { ItemStack(Material.WITHER_ROSE) },
	typeCategory = TypeCategory.MISC,
	color = "#d0e39d",
	overridePermission = "ion.ships.eventship",
	eventShip = true,
	powerOverrider = 2.0,
	sinkProvider = SinkProvider.SinkProviders.NO_REMOVAL,
	balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::testing,
	disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	),
	AI_SHIP(
		displayName = "AI Ship",
		needsFuel = false,
		tech2 = false,
		minSize = 50,
		maxSize = 48000,
		minLevel = 1000,
		containerPercent = 0.025,
		concretePercent = 0.0,
		crateLimitMultiplier = 0.5,
		menuItemRaw = { ItemStack(Material.SCULK) },
		typeCategory = TypeCategory.MISC,
		color = "#d000d0",
		requiredPermission = "ion.ships.ai",
        overridePermission = "ion.ships.aiship",
		sinkProvider = SinkProvider.SinkProviders.NO_REMOVAL,
		balancingSupplier = ConfigurationFiles.starshipBalancing().shipClasses::unidentified,
		disallowedWorldFlags = setOf(WorldFlag.PLANET_SIEGE_WORLD),
	);

	val balancing get() = balancingSupplier.get()

	val textColor = TextColor.fromHexString(color)!!

	val displayNameMiniMessage: String get() = "<$color>$displayName</$color>"
	val displayNameComponent: Component get() = text(displayName, TextColor.fromHexString(color))

	val menuItem: ItemStack get() = menuItemRaw.get()
		.updateDisplayName(displayNameComponent)
		.updateLore(listOf(
			ofChildren(text("Minimum Block Count: ", HE_MEDIUM_GRAY), text(minSize, AQUA), newline()),
			ofChildren(text("Maximum Block Count: ", HE_MEDIUM_GRAY), text(maxSize, AQUA), newline()),
			empty(),
			text("Right click to view subclasses", AQUA),
			text("Left click to select", AQUA),
		))

	fun canUse(player: Player): Boolean = (if (requiredPermission == null) true else player.hasPermission(requiredPermission))
		&& (player.hasPermission("starships.anyship") || player.hasPermission(overridePermission) || Levels[player] >= minLevel)

	fun canPilotIn(world: IonWorld): Boolean {
		val flags = world.configuration.flags

		// TODO: band-aid to override space world requirements in creative
		if (world.hasFlag(WorldFlag.NO_SUPERCAPITAL_REQUIREMENTS)) return true
		if (requiredWorldFlags.toMutableSet().subtract(flags).isNotEmpty()) return false
		return disallowedWorldFlags.none { flags.contains(it) }
	}

	companion object {
		fun getUnlockedTypes(player: Player): List<StarshipType> = entries
			.filter { it.canUse(player) }
			.filter { !it.eventShip.and(!player.hasPermission("ion.ships.eventship")) }
			.sortedBy { it.minLevel }
	}
}
