main: net.horizonsend.ion.server.IonServer

version: unspecified
api-version: 1.19
load: POSTWORLD

name: Ion
website: https://horizonsend.net
author: Peter Crawley
authors:
  - MicleBrick
  - Sciath
  - Gutin1 (Gutin)
  - quinnbuskus (liluzivirt)
  - trainb0y
  - ItsAlreadyGold
  - PiggleMcDiggle (DoctorXeno)
  - Vandrayk
  - EmeraldBlade (EmeraldsGaming)

depend:
  - WorldEdit

softdepend:
  - Citizens
  - DiscordSRV
  - LuckPerms
  - Multiverse-Core
  - Vault
  - dynmap

libraries:
  - "com.github.stefvanschie.inventoryframework:IF:0.5.8"
  - "com.daveanthonythomas.moshipack:moshipack:1.0.1"
  - "com.googlecode.cqengine:cqengine:3.6.0"
  - "io.github.config4k:config4k:0.5.0"

  - "org.spongepowered:configurate-extra-kotlin:4.1.2"
  - "org.spongepowered:configurate-hocon:4.1.2"

  - "org.jetbrains.kotlin:kotlin-reflect:1.7.22"
  - "org.jetbrains.kotlin:kotlin-stdlib:1.7.22"

  - "org.litote.kmongo:kmongo:4.10.3"
  - "redis.clients:jedis:4.3.1"