main: net.horizonsend.ion.proxy.IonProxy

version: unspecified

name: Ion
website: https://horizonsend.net
author: Peter Crawley
authors:
  - MicleBrick
  - Sciath
  - Gutin1 (Gutin)
  - quinnbuskus (liluzivirt)
  - trainb0y
  - ItsAlreadyGold
  - PiggleMcDiggle (DoctorXeno)
  - Vandrayk
  - EmeraldBlade (EmeraldsGaming)

libraries:
  - "net.dv8tion:JDA:5.0.0-beta.1"

  - "org.spongepowered:configurate-extra-kotlin:4.1.2"
  - "org.spongepowered:configurate-hocon:4.1.2"

  - "org.jetbrains.kotlin:kotlin-reflect:1.7.22"
  - "org.jetbrains.kotlin:kotlin-stdlib:1.7.22"

  - "org.litote.kmongo:kmongo:4.8.0"
  - "redis.clients:jedis:4.10.3"