package net.horizonsend.ion.server.features.world

enum class WorldFlag {
    SPACE_WORLD,
	SAFE_WORLD,
	REGION_WORLD_WARD,
	REGION_WORLD_BREACH,
	REGION_WORLD_MONOLITH,
	REGION_WORLD_FRACTURE,
	REGION_WORLD_SPINE,
	EXTRA_RENDER_WORLD,
	DOMINION_WORLD,
	ADMIN_ONLY_WORLD,
	PLANET_WORLD,
	SPEEDERS_EXPLODE,
	ALLOW_MINING_LASERS,
    HYPERSPACE_WORLD,
    ALLOW_SPACE_STATIONS,
    ALLOW_AI_SPAWNS,
	AI_ARENA,
	ARENA,
	NO_SHIP_LOCKS,
	NOT_SECURE,
	NO_SUPERCAPITAL_REQUIREMENTS,
	AREA_SHIELDS_DISABLED,
	TUTORIAL_WORLD,
	PLANET_SIEGE_WORLD,
}

enum class SpaceRegion {
	WARD,
	BREACH,
	MONOLITH,
	FRACTURE,
	SPINE,
	NONE
}
